baseURL = 'https://Shawn-TKD.github.io/Blog/'
 languageCode = 'zh-cn'
 title = '肖恩的部落格'
 publishDir = "docs"
author = 'Shawn'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
description = '我是Shawn 这是我的blog 我专注在区块链、AI和消费品投资'
